language: go

go:
  - 1.3
  - tip

env:
  - "PATH=$HOME/gopath/bin:$PATH"

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - echo -e "mode: count" > coverage.out
  - go test -v -covermode=count -coverprofile=magic_packet.out
  - go test -v ./cmd/wol -covermode=count -coverprofile=wol.out
  - cat magic_packet.out | tail -n +2 >> coverage.out
  - cat wol.out | tail -n +2 >> coverage.out
  - rm magic_packet.out wol.out
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
